import logging
from typing import Any, Dict, List

import numpy as np
import torch
import torchaudio
from sklearn.cluster import AgglomerativeClustering
from speechbrain.pretrained import EncoderClassifier

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - [%(name)s] - %(message)s")
logger = logging.getLogger(__name__)

class SpeakerDiarizer:
    """
    A speaker diarization module that clusters word-level audio segments into contiguous speaker blocks.
    """
    def __init__(self, device: str = "cuda"):

        self.device = device if torch.cuda.is_available() else "cpu"

        logger.info(f"Loading SpeechBrain ECAPA-TDNN model on {self.device}...")

        try:

            self.classifier = EncoderClassifier.from_hparams(
                source = "speechbrain/spkrec-ecapa-voxceleb",
                run_opts = {"device": self.device},
                savedir = "pretrained_models/spkrec-ecapa-voxceleb"
            )

            logger.info("SpeechBrain model loaded successfully.")

        except Exception as e:
            logger.error(f"Failed to load SpeechBrain model: {str(e)}")
            raise RuntimeError(f"Diarization Model initialization failed: {str(e)}")


    def _extract_embedding(self, audio_tensor: torch.Tensor, sample_rate: int,start_sec: float, end_sec: float ) -> np.ndarray:

        """
        Extracts a speaker embedding for a specific time segment with context padding.
        """
        # padding = 0.4 seconds on both sides gives the model enough acoustic context

        padding = 0.4
        total_samples = audio_tensor.shape[1]

        start_sample = max(0, int((start_sec -  padding) * sample_rate))
        end_sample = min(total_samples, int((end_sec + padding) * sample_rate))

        if end_sample <= start_sample:
            return np.zeros((192,))

        chunk = audio_tensor[:, start_sample:end_sample]

        with torch.no_grad():
            embeddings = self.classifier.encode_batch(chunk)

        return embeddings.squeeze().cpu().numpy()

    def process(self, audio_path:str, words_data: List[Dict[str, Any]], num_speakers: int = 2) -> List[Dict[str, Any]]:
        """
        Takes word-level timestamps, extracts embeddings, clusters them, and merges
        contiguous words into coherent speaker blocks.
        
        Args:
            audio_path (str): Path to the audio file.
            words_data (List[Dict]): Word timestamps generated by the Transcriber.
            
        Returns:
            List[Dict[str, Any]]: Final segments formatted as expected by the API.
        """

        if not words_data:
            logger.warning("No words data provided. Returning empty segments.")
            return []
        
        logger.info(f"Loading audio file for diarization: {audio_path}")

        try:
            audio_tensor, sample_rate = torchaudio.load(audio_path)

            if sample_rate != 16000:
                resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=16000)
                audio_tensor = resampler(audio_tensor)
                sample_rate = 16000

            if audio_tensor.shape[0] > 1:
                audio_tensor = torch.mean(audio_tensor, dim=0, keepdim=True)

        except Exception as e:
            logger.error(f"Failed to load audio for processing: {str(e)}")
            raise

        logger.info(f"Extracting embeddings for {len(words_data)} words...")
        embeddings = []
        valid_words = []

        for w in words_data:
            emb = self._extract_embedding(audio_tensor, sample_rate, w["start"], w["end"])
            if np.sum(np.abs(emb)) > 0:
                embeddings.append(emb)
                valid_words.append(w)

        if not embeddings:
            logger.error("Failed to extract any valid embeddings.")
            return []

        logger.info(f"Clustering embeddings into {num_speakers} speakers...")
        clusterer = AgglomerativeClustering(n_clusters=num_speakers, metric='cosine', linkage='average')
        labels = clusterer.fit_predict(embeddings)

        logger.info("Merging clustered words into contiguous segments...")
        segments = []
        current_segment = {"speaker": "", "start": 0.0, "end": 0.0, "text": ""}
        current_label = None

        for word, label in zip(valid_words, labels):
            speaker_id = f"speaker_{label}"

            if speaker_id != current_label:
                if current_segment["text"]:
                    segments.append(current_segment)

                current_segment = {
                    "speaker": speaker_id,
                    "start": word["start"],
                    "end": word["end"],
                    "text": word["word"]
                }

                current_label = speaker_id

            else:
                current_segment["text"] += f" {word['word']}"
                current_segment["end"] = word ["end"]

        if current_segment["text"]:
            segments.append(current_segment)

        logger.info(f"Diarization complete. Generated {len(segments)} contiguous segments.")
        return segments